name: Build anki folder

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or Tag to build'
        required: true
        default: 'Viccyware-tester'
  push:
    tags:
      - '*'

jobs:
  make_victor:
    runs-on: [self-hosted, linux]
    steps:
    - name: Determine Checkout Ref
      id: get-ref
      run: |
        if [ -n "${{ github.event.inputs.ref }}" ]; then
          echo "ref=${{ github.event.inputs.ref }}" >> $GITHUB_OUTPUT
        elif [ -n "${{ github.ref_name }}" ]; then
          echo "ref=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        else
          echo "ref=Viccyware-tester" >> $GITHUB_OUTPUT
        fi
  
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        clean: false
        ref: ${{ steps.get-ref.outputs.ref }}
        submodules: recursive
        fetch-depth: 0

    - name: Build inside Docker
      run: |
         chmod +rwx build/actions.sh
         ./build/actions.sh

    - name: Stage anki folder
      run: |
         ./project/victor/scripts/stage.sh -c Release -b
         cd _build/staging/Release/
         tar czf anki.tar.gz anki/

    - name: Upload anki folder
      uses: actions/upload-artifact@v4
      with:
        name: anki-folder-${{ steps.get-ref.outputs.ref }}
        path: _build/staging/Release/anki.tar.gz
        retention-days: 30
        if-no-files-found: warn

